from os.path import join
import os
import numpy as np
import sys


configfile: "config.yaml"


WINDOWS = ["1e5", "1e6"]

"""
rules:
STAR
    - index: generate STAR index with Gencode v33, with annotation GTF as recommended
    - See step 1-5 for running STAR, 1st and 2nd pass, WASP filter; Leafcutter bam2junc
Leafcutter combined ancestry
    - cluster: note some output files are not specified here
    - remove_chr: 
    - write_chr_blacklist
    - pheno_prep: note some output files are not specified here
    - bgzip_tabix
    - concat
    - pheno_process
    - cov
    - fastqtl_nominal
    - merge_nominal
    - call_nominal
    - fastqtl_perm
    - merge_perm
    - call_perm
Separate ancestry
    - ancestry_pheno
    - ancestry_cov
    - ancestry_fastqtl_nominal
    - ancestry_merge_nominal
    - ancestry_call_nominal
    - ancestry_fastqtl_perm
    - ancestry_merge_perm
    - ancestry_call_perm
Intron annotation
    - prepare_leafviz_annot
    - annotate_intron
    - summarise_annot
GTEx way
    - prepare_leafviz_annot_exons: add gene_id in all_exons file
    - map_clusters_to_genes
    - make_grp_and_bed_file
    - fastqtl_grp_perm
Conditional 
    - permutations_all_threshold: compute a npval threshold for all tested introns
    - conditional: run QTLtools conditional pass
    - get_top_variants: get top variants per rank
susie finemapping
    - vcf_to_dosage
    - make_susie_meta
    - make_susie_expr
    - run_susie
    - merge_susie
    - sort_susie
Torus: functional enrichment
    - fastqtl_calculate_sebeta
    - merge_sebeta
    - run_torus
"""


rule all:
    input:
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/{file}",
        #     num_hcp=np.arange(5, 51, 5),
        #     window=WINDOWS,
        #     file=[
        #         "all_assoc.txt.gz",
        #         "significant_assoc.txt",
        #         "significant_feature_count.txt",
        #     ],
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/all_assoc.txt.gz",
        #     zip,
        #     best_num_hcp=[35, 40],
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/sig_pheno.txt",
        #     zip,
        #     best_num_hcp=[35, 40],
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz",
        #     chunk=np.arange(1, 101, 1),
        #     ancestry="eur",
        #     num_hcp=np.arange(5, 51, 5),
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz.done",
        #     chunk=np.arange(1, 101, 1),
        #     ancestry="eur",
        #     num_hcp=np.arange(5, 51, 5),
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz",
        #     chunk=np.arange(1, 95, 1),
        #     ancestry=["amr", "afr"],
        #     num_hcp=np.arange(2, 21, 2),
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz.done",
        #     chunk=np.arange(1, 95, 1),
        #     ancestry=["amr", "afr"],
        #     num_hcp=np.arange(2, 21, 2),
        #     window=WINDOWS,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/{file}",
        #     ancestry="eur",
        #     num_hcp=np.arange(5, 51, 5),
        #     window=WINDOWS,
        #     file=[
        #         "all_assoc.txt.gz",
        #         "significant_assoc.txt",
        #         "significant_feature_count.txt",
        #     ],
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/{file}",
        #     ancestry=["amr", "afr"],
        #     num_hcp=np.arange(2, 21, 2),
        #     window=WINDOWS,
        #     file=[
        #         "all_assoc.txt.gz",
        #         "significant_assoc.txt",
        #         "significant_feature_count.txt",
        #     ],
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/{file}",
        #     file=["all_assoc.txt.gz", "sig_pheno.txt"],
        #     ancestry="eur",
        #     num_hcp=25,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/{file}",
        #     file=["all_assoc.txt.gz", "sig_pheno.txt"],
        #     ancestry="amr",
        #     num_hcp=10,
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/{file}",
        #     file=["all_assoc.txt.gz", "sig_pheno.txt"],
        #     ancestry="afr",
        #     num_hcp=12,
        # ),
        # "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/all.introns.RData",
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz",
        #     num_hcp=40,
        #     window="1e6",
        #     chunk=np.setdiff1d(np.arange(1, 301, 1), np.array([54, 55, 56, 57, 58])),
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.log",
        #     num_hcp=40,
        #     window="1e6",
        #     chunk=np.setdiff1d(np.arange(1, 301, 1), np.array([54, 55, 56, 57, 58])),
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz.done",
        #     num_hcp=40,
        #     window="1e6",
        #     chunk=np.setdiff1d(np.arange(1, 301, 1), np.array([54, 55, 56, 57, 58])),
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{window}/{file}",
        #     window=WINDOWS,
        #     file=["conditional_full.txt", "conditional_top_variants.txt"],
        # ),
        # expand(
        #     "/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/{file}",
        #     file=[
        #         "4_columns_intron.tsv",
        #         "sample_list_intron.tsv",
        #         "header_intron.tsv",
        #         "header_row_intron.tsv.gz",
        #         "dose_matrix_intron.tsv.gz",
        #         "filtered.hg19.sorted.removeRel.dose.tsv.gz",
        #         "filtered.hg19.sorted.removeRel.dose.tsv.gz.tbi",
        #     ],
        # ),
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/torus.out",


rule index:
    input:
        config["GENOME_FASTA"],
        config["GTF_FILE"],
    output:
        "/u/project/gandalm/cindywen/isoform_twas/star/gencodev33_STARindex/SAindex",
    resources:
        mem_gb=4,
        time_min=120,
        num_cores=8,
    shell:
        """
        {config[STAR]} --runThreadN {resources.num_cores} \
            --runMode genomeGenerate \
            --genomeDir /u/project/gandalm/cindywen/isoform_twas/star/gencodev33_STARindex \
            --genomeFastaFiles {config[GENOME_FASTA]} \
            --sjdbGTFfile {config[GTF_FILE]} \
            --sjdbOverhang 100
        """


rule cluster:
    input:
        "juncfiles.txt",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_{file}",
            file=[
                "pooled",
                "refined",
                "sortedlibs",
                "perind.counts.gz",
                "perind_numers.counts.gz",
            ],
        ),
    resources:
        mem_gb=6,
        time_min=150,
    params:
        script=config["LEAFCUTTER"] + "clustering/leafcutter_cluster.py",
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load python/2.7.16
        mkdir -p {params.outdir}
        python {params.script} \
            -j {input[0]} \
            -m 50 \
            -l 500000 \
            -r {params.outdir}
        """


rule remove_chr:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz",
    resources:
        mem_gb=6,
        time_min=120,
    shell:
        """
        zcat {input[0]} | sed '2, $s/chr//' | gzip -c > {output[0]}
        """


rule write_chr_blacklist:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz",
    output:
        "chr_remove.txt",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        script="./scripts/write_chr_blacklist.R",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript {params.script} \
            --input {input[0]} \
            --output {output[0]}
        """


rule pheno_prep:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz",
        "chr_remove.txt",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz{file}",
            file=["_prepare.sh", ".PCs", ".ave"],
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.phen_chr{chr_num}",
            chr_num=np.arange(1, 23, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}",
            chr_num=np.arange(1, 23, 1),
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        script=config["LEAFCUTTER"] + "scripts/prepare_phenotype_table.py",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load python/2.7.16
        module load htslib/1.9
        python {params.script} {input[0]} \
            --ChromosomeBlackList {input[1]}
        """


rule bgzip_tabix:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz_prepare.sh",
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}",
            chr_num=np.arange(1, 23, 1),
        ),
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}.gz",
            chr_num=np.arange(1, 23, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}.gz.tbi",
            chr_num=np.arange(1, 23, 1),
        ),
    resources:
        mem_gb=6,
        time_min=120,
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load htslib/1.9
        bash {input[0]}
        """


rule concat:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}.gz",
            chr_num=np.arange(1, 23, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_chr{chr_num}.gz.tbi",
            chr_num=np.arange(1, 23, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all.gz.tbi",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        prefix="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load htslib/1.9
        for i in {{1..22}}; do
        zcat {params.prefix}_chr${{i}}.gz | bgzip -f >> {params.prefix}_all.gz
        done
        tabix -p bed {params.prefix}_all.gz
        """


rule pheno_process:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all.gz.tbi",
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/geno_subj/geno_subj_{study}.txt",
            study=["walker", "obrien", "werling", "hdbr", "libd"],
        ),
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_{file}",
            file=[
                "fixSubj.tsv",
                "fixSubj_combat.tsv",
                "fixSubj_combat.bed.gz",
                "fixSubj_combat.bed.gz.tbi",
            ],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        script="./scripts/pheno_process.R",
        prefix="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all",
        geno_subj_dir="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/geno_subj/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        module load htslib/1.9
        Rscript {params.script} \
            --prefix {params.prefix} \
            --geno_subj_dir {params.geno_subj_dir}
        bgzip -f {params.prefix}_fixSubj_combat.bed
        tabix -p bed {params.prefix}_fixSubj_combat.bed.gz
        """


rule cov:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_fixSubj_combat.tsv",
        picard=(
            "/u/project/gandalm/cindywen/isoform_twas/picard/picard_QC_compiled.tsv"
        ),
        geno_pc="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/pca/data.ref.eigenvec",
        meta="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/metadata_inferSex.tsv",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{num_hcp}hcp_cov.txt",
    resources:
        mem_gb=8,
        time_min=120,
    params:
        script="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/cov.R",
        num_gpc=5,
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        mkdir -p {params.outdir}
        Rscript {params.script} \
            --num_hcp {wildcards.num_hcp} \
            --expr {input.expr} \
            --picard {input.picard} \
            --geno_pc {input.geno_pc} \
            --meta {input.meta} \
            --num_gpc {params.num_gpc} \
            --outdir {params.outdir}
        """


rule fastqtl_nominal:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_fixSubj_combat.bed.gz",
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{num_hcp}hcp_cov.txt",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=4,
        time_min=150,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}",
    shell:
        """
        mkdir -p {params.outdir}
        {config[FASTQTL]} --vcf {input.geno} \
                          --bed {input.expr} \
                          --cov {input.cov} \
                          --out {output[0]} \
                          --chunk {wildcards.chunk} 100 \
                          --seed 123 \
                          --window {wildcards.window} \
                          --normal \
                          --exclude-samples {input.rel_file}
        touch {output[0]}.done
        """


rule merge_nominal:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{{num_hcp}}hcp_{{window}}/chunk{chunk}.txt.gz.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/all.chunks.txt.gz",
    resources:
        mem_gb=24,
        time_min=160,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/",
    shell:
        """
        zcat {params.outdir}chunk*.txt.gz | gzip -c > {params.outdir}all.chunks.txt.gz
        """


rule call_nominal:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/all.chunks.txt.gz",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{{num_hcp}}hcp_{{window}}/{file}",
            file=[
                "all_assoc.txt.gz",
                "significant_assoc.txt",
                "significant_feature_count.txt",
            ],
        ),
    resources:
        mem_gb=12,
        time_min=200,
        num_cores=16,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_{num_hcp}hcp_{window}/",
        script="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/call_nominal.R",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        module load htslib/1.9

        Rscript {params.script} \
            --outdir {params.outdir}
        gzip {params.outdir}all_assoc.txt
        # bgzip {params.outdir}all_assoc.txt
        """


rule fastqtl_perm:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_fixSubj_combat.bed.gz",
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{best_num_hcp}hcp_cov.txt",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=6,
        time_min=1440,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}",
    shell:
        """
        mkdir -p {params.outdir}
        {config[FASTQTL]} --vcf {input.geno} \
                          --bed {input.expr} \
                          --cov {input.cov} \
                          --permute 1000 10000 \
                          --out {output[0]} \
                          --chunk {wildcards.chunk} 100 \
                          --seed 123 \
                          --window {wildcards.window} \
                          --normal \
                          --exclude-samples {input.rel_file}
        touch {output[0]}.done
        """


rule merge_perm:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{{best_num_hcp}}hcp_{{window}}/chunk{chunk}.txt.gz",
            chunk=np.arange(1, 101, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{{best_num_hcp}}hcp_{{window}}/chunk{chunk}.txt.gz.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/all.chunks.txt.gz",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/",
    shell:
        """
        zcat {params.outdir}chunk*.txt.gz | gzip -c > {params.outdir}all.chunks.txt.gz
        """


rule call_perm:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/all.chunks.txt.gz",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{{best_num_hcp}}hcp_{{window}}/{file}",
            file=["all_assoc.txt.gz", "sig_pheno.txt"],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_{best_num_hcp}hcp_{window}/",
        script=(
            "/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/call_perm.R"
        ),
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0

        Rscript {params.script} \
            --outdir {params.outdir}
        gzip {params.outdir}all_assoc.txt
        """


rule ancestry_pheno:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_{file}",
            file=[
                "fixSubj.tsv",
                "fixSubj_combat.tsv",
                "fixSubj_combat.bed.gz",
                "fixSubj_combat.bed.gz.tbi",
            ],
        ),
        "/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/ancestry_list/list.{ancestry}.tsv",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{{ancestry}}/{file}",
            file=[
                "lc.tsv",
                "lc_combat.tsv",
                "lc_combat.bed.gz",
                "lc_combat.bed.gz.tbi",
            ],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        script="scripts/ancestry_lc.R",
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/",
        combined_dir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        module load htslib/1.9

        mkdir -p {params.outdir}
        Rscript {params.script} \
            --combined_dir {params.combined_dir} \
            --subj_list {input[4]} \
            --outdir {params.outdir}
        bgzip {params.outdir}lc_combat.bed
        tabix -p bed {params.outdir}lc_combat.bed.gz
        """


rule ancestry_cov:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/lc_combat.tsv",
        picard=(
            "/u/project/gandalm/cindywen/isoform_twas/picard/picard_QC_compiled.tsv"
        ),
        geno_pc="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/{ancestry}/pca/data.ref.eigenvec",
        meta="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/metadata_inferSex.tsv",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/{num_hcp}HCP_cov.txt",
    resources:
        mem_gb=8,
        time_min=60,
    params:
        script="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/ancestry_cov.R",
        num_gpc=5,
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0

        Rscript {params.script} \
            --num_hcp {wildcards.num_hcp} \
            --expr {input.expr} \
            --picard {input.picard} \
            --geno_pc {input.geno_pc} \
            --meta {input.meta} \
            --num_gpc {params.num_gpc} \
            --outdir {params.outdir}
        """


rule ancestry_fastqtl_nominal:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/lc_combat.bed.gz",
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/{ancestry}/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/{num_hcp}HCP_cov.txt",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=4,
        time_min=180,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}",
    shell:
        """
        mkdir -p {params.outdir}
        {config[FASTQTL]} --vcf {input.geno} \
                          --bed {input.expr} \
                          --cov {input.cov} \
                          --out {output[0]} \
                          --chunk {wildcards.chunk} 100 \
                          --seed 123 \
                          --window {wildcards.window} \
                          --normal \
                          --exclude-samples {input.rel_file}
        touch {output[0]}.done
        """


rule ancestry_merge_nominal:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_nominal_{{num_hcp}}HCP_{{window}}/chunk{chunk}.txt.gz",
            chunk=np.arange(1, 101, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_nominal_{{num_hcp}}HCP_{{window}}/chunk{chunk}.txt.gz.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/all.chunks.txt.gz",
    resources:
        mem_gb=24,
        time_min=160,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/",
    shell:
        """
        zcat {params.outdir}chunk*.txt.gz | gzip -c > {params.outdir}all.chunks.txt.gz
        """


rule ancestry_call_nominal:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/all.chunks.txt.gz",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_nominal_{{num_hcp}}HCP_{{window}}/{file}",
            file=[
                "all_assoc.txt.gz",
                "significant_assoc.txt",
                "significant_feature_count.txt",
            ],
        ),
    resources:
        mem_gb=4,
        time_min=250,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_nominal_{num_hcp}HCP_{window}/",
        script="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/call_nominal.R",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0

        Rscript {params.script} \
            --outdir {params.outdir}
        gzip {params.outdir}all_assoc.txt
        """


rule ancestry_fastqtl_perm:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/lc_combat.bed.gz",
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/{ancestry}/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{ancestry}/{num_hcp}HCP_cov.txt",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=6,
        time_min=480,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}",
    shell:
        """
        mkdir -p {params.outdir}
        {config[FASTQTL]} --vcf {input.geno} \
                          --bed {input.expr} \
                          --cov {input.cov} \
                          --permute 1000 10000 \
                          --out {output[0]} \
                          --chunk {wildcards.chunk} 100 \
                          --seed 123 \
                          --window {wildcards.window} \
                          --normal \
                          --exclude-samples {input.rel_file}
        touch {output[0]}.done
        """


rule ancestry_merge_perm:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_perm_{{num_hcp}}HCP_{{window}}/chunk{chunk}.txt.gz",
            chunk=np.arange(1, 101, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_perm_{{num_hcp}}HCP_{{window}}/chunk{chunk}.txt.gz.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/all.chunks.txt.gz",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/",
    shell:
        """
        zcat {params.outdir}chunk*.txt.gz | gzip -c > {params.outdir}all.chunks.txt.gz
        """


rule ancestry_call_perm:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/all.chunks.txt.gz",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{{ancestry}}_perm_{{num_hcp}}HCP_{{window}}/{file}",
            file=["all_assoc.txt.gz", "sig_pheno.txt"],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/{ancestry}_perm_{num_hcp}HCP_{window}/",
        script=(
            "/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/call_perm.R"
        ),
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0

        Rscript {params.script} \
            --outdir {params.outdir}
        gzip {params.outdir}all_assoc.txt
        """


############################## Intron annotation ##############################
rule prepare_leafviz_annot:
    input:
        config["GTF_FILE"],
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_{file}",
            file=[
                "all_introns.bed.gz",
                "threeprime.bed.gz",
                "fiveprime.bed.gz",
                "all_exons.txt.gz",
            ],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        out_dir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/",
        out_prefix="gencode_v33lift37",
        script=config["LEAFCUTTER"] + "leafviz/gtf2leafcutter.pl",
    shell:
        """ 
        . /u/local/Modules/default/init/modules.sh
        module load perl/5.10.1
        mkdir -p {params.out_dir}
        {params.script} -o {params.out_dir}{params.out_prefix} {config[GTF_FILE]}
        """


rule annotate_intron:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_{file}",
            file=[
                "all_introns.bed.gz",
                "threeprime.bed.gz",
                "fiveprime.bed.gz",
                "all_exons.txt.gz",
            ],
        ),
        counts="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind_numers.counts.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafviz.RData",
    resources:
        mem_gb=4,
        num_cores=10,
        time_min=480,
    params:
        script="scripts/annotate_intron.R",
        annot="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37",
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript {params.script} \
            --annot {params.annot} \
            --counts {input.counts} \
            --outdir {params.outdir}
        """


rule summarise_annot:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafviz.RData",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/all.introns.RData",
    resources:
        mem_gb=4,
        num_cores=4,
        time_min=360,
    params:
        script="scripts/summarise_annot.R",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript {params.script} \
            --annot {input[0]}
        """


############################## GTEx way, grouped permutations ##############################
# original all_exons file has only gene names which have duplicates, here add gene ID
# this is very slow. Exon big file
# rule make_all_exons:
#     input:
#         "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_all_exons.txt.gz",
#     output:
#         "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_all_exons_withENSG.txt.gz",
#     resources:
#         mem_gb=4,
#         time_min=240,
#         num_cores=6
#     params:
#         prefix="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_all_exons_withENSG"
#     shell:
#         """
#         . /u/local/Modules/default/init/modules.sh
#         module load R/3.6.0
#         module load htslib/1.9
#         Rscript scripts/make_all_exons.R \
#             --out {params.prefix} \
#             --gtf {config[GTF_FILE]}
#         bgzip {params.prefix}.txt
#         """


# Use new leafcutter script
rule prepare_leafviz_annot_exons:
    input:
        config["GTF_FILE"],
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_withENSG_all_exons.txt.gz",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        out_dir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/",
        out_prefix="gencode_v33lift37_withENSG",
        script="scripts/gtf2leafcutter_all_exons_ensg.pl",
    shell:
        """ 
        . /u/local/Modules/default/init/modules.sh
        module load perl/5.10.1
        mkdir -p {params.out_dir}
        {params.script} -o {params.out_dir}{params.out_prefix} {config[GTF_FILE]}
        """


rule map_clusters_to_genes:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/gencode_v33lift37_withENSG_all_exons.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafcutter_clusters_to_genes.txt",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        out_dir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot",
        out_file="leafcutter_clusters_to_genes.txt",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript scripts/map_clusters_to_genes.R \
            --intron_counts_file {input[1]} \
            --exon_file {input[0]} \
            --output_dir {params.out_dir} \
            --output_name {params.out_file}
        """


# grouping file: intron to gene mappings
# BED file: add gene to intron ID, use gene coordinate as feature coordinate
rule make_grp_and_bed_file:
    input:
        cluster2gene="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafcutter_clusters_to_genes.txt",
        bed="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_fixSubj_combat.bed.gz",
        info="/u/project/gandalm/cindywen/isoform_twas/salmon/gencode.v33lift37.annotation.gene.info.tsv",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafcutter.phenotype_groups.txt",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_grp.bed.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_grp.bed.gz.tbi",
    resources:
        mem_gb=8,
        time_min=60,
    params:
        bed_out="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_grp.bed",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        module load htslib/1.9
        Rscript scripts/make_grp_and_bed_file.R \
            --cluster_to_gene {input.cluster2gene} \
            --bed {input.bed} \
            --info {input.info} \
            --grp {output[0]} \
            --bed_out {params.bed_out}
        bgzip {params.bed_out}
        tabix -p bed {params.bed_out}.gz
        """


rule run_fastqtl_grp_perm:
    input:
        expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_grp.bed.gz",
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/{num_hcp}hcp_cov.txt",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
        grp_file="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/leafviz_annot/leafcutter.phenotype_groups.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.log",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=4,
        time_min=720,
        num_cores=10,
    params:
        out_dir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_grp_perm_{num_hcp}hcp_{window}/",
    shell:
        """
        mkdir -p {params.out_dir}
        . /u/local/Modules/default/init/modules.sh
        module load gcc/9.3.0
        mkdir -p {params.out_dir}
        /u/project/gandalm/cindywen/isoform_twas/sqtl_new/fastqtl-gtex/bin/fastQTL.static \
            --vcf {input.geno} \
            --bed {input.expr} \
            --window {wildcards.window} \
            --cov {input.cov} \
            --grp {input.grp_file} \
            --permute 1000 10000 \
            --seed 123 \
            --exclude-samples {input.rel_file} \
            --chunk {wildcards.chunk} 1000 \
            --out {output[0]} \
            --log {output[1]} \
            --normal
        touch {output[2]}
        """


############################## QTLtools conditional pass ##############################
rule permutations_all_threshold:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_35hcp_{window}/all.chunks.txt.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_35hcp_{window}/permutations_all_threshold.txt.gz",
    resources:
        mem_gb=6,
        time_min=120,
    params:
        script="/u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/permutations_all_threshold.R",
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_35hcp_{window}/",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript {params.script} \
            --outdir {params.outdir}
        gzip {params.outdir}permutations_all_threshold.txt
        """


rule make_qtltools_bed:
    input:
        fastqtl_expr="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/leafcutter_perind.counts.nochr.gz.qqnorm_all_fixSubj_combat.bed.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/qtltools.bed.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/qtltools.bed.gz.tbi",
    resources:
        mem_gb=6,
        time_min=120,
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load htslib/1.9
        zcat {input.fastqtl_expr} | awk '{{ $4=$4" . +"; print $0 }}' | tr " " "\t" | bgzip -c > {output[0]}
        tabix -p bed {output[0]}
        """


rule conditional:
    input:
        expr=(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/cluster/qtltools.bed.gz"
        ),
        geno="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel.vcf.gz",
        cov="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/data/35hcp_cov.txt",
        threshold="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_perm_35hcp_{window}/permutations_all_threshold.txt.gz",
        rel_file="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/related.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{window}/chunk{chunk}.txt",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{window}/chunk{chunk}.txt.done",
    resources:
        mem_gb=6,
        time_min=480,
        num_cores=6,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{window}/",
    shell:
        """
        mkdir -p {params.outdir}
        {config[QTLTOOLS]} cis \
            --vcf {input.geno} \
            --bed {input.expr} \
            --cov {input.cov} \
            --mapping {input.threshold} \
            --chunk {wildcards.chunk} 100 \
            --out {output[0]} \
            --exclude-samples {input.rel_file} \
            --seed 123 \
            --window {wildcards.window} \
            --normal
        touch {output[1]}
        """


rule get_top_variants:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{{window}}/chunk{chunk}.txt.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{{window}}/{file}",
            file=["conditional_full.txt", "conditional_top_variants.txt"],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        outdir="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_conditional_35hcp_{window}/",
    shell:
        """
        cat {params.outdir}chunk*.txt > {params.outdir}conditional_full.txt
        cat {params.outdir}conditional_full.txt | awk '{{ if ($19 == 1) print $0}}' > {params.outdir}conditional_top_variants.txt
        """


################################### susie finemapping ###################################
rule vcf_to_dosage:
    input:
        vcf="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel.vcf.gz",
    output:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/{file}",
            file=[
                "4_columns_intron.tsv",
                "sample_list_intron.tsv",
                "header_intron.tsv",
                "header_row_intron.tsv.gz",
                "dose_matrix_intron.tsv.gz",
                "filtered.hg19.sorted.removeRel.dose.tsv.gz",
                "filtered.hg19.sorted.removeRel.dose.tsv.gz.tbi",
            ],
        ),
    resources:
        mem_gb=6,
        time_min=120,
    params:
        prefix="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/filtered.hg19.sorted.removeRel",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load bcftools/1.9
        module load htslib/1.9

        # Extract header
        printf 'CHROM\nPOS\nREF\nALT\n' > {output[0]}
        bcftools query -l {input.vcf} > {output[1]}
        cat {output[0]} {output[1]} > {output[2]}
        {config[CSVTK]} transpose {output[2]} -T | gzip > {output[3]}

        # Extract dosage and merge
        bcftools +dosage {input.vcf} -- -t GT | tail -n+2 | gzip > {output[4]}
        zcat {output[3]} {output[4]} | bgzip > {params.prefix}.dose.tsv.gz
        tabix -s1 -b2 -e2 -S1 {params.prefix}.dose.tsv.gz
        """


################################### Torus functional enrichment ###################################
rule fastqtl_calculate_sebeta:
    input:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/significant_assoc.txt",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_chunk{chunk}.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_chunk{chunk}.txt.gz.done",
    resources:
        mem_gb=4,
        time_min=240,
        num_cores=6,
    params:
        prefix="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_chunk{chunk}",
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load R/3.6.0
        Rscript /u/project/gandalm/cindywen/isoform_twas/eqtl_new/code/scripts/calculate_sebeta.R \
            --input {input[0]} \
            --output {params.prefix}.txt \
            --sig {input[1]}
        gzip {params.prefix}.txt
        touch {params.prefix}.txt.gz.done
        """


rule merge_sebeta:
    input:
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_chunk{chunk}.txt.gz",
            chunk=np.arange(1, 101, 1),
        ),
        expand(
            "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_chunk{chunk}.txt.gz.done",
            chunk=np.arange(1, 101, 1),
        ),
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_all_chunks.txt.gz",
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_all_chunks.txt.gz.done",
    resources:
        mem_gb=4,
        time_min=240,
        num_cores=6,
    params:
        prefix="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_",
    shell:
        """
        zcat {params.prefix}chunk*.txt.gz | gzip -c > {params.prefix}all_chunks.txt.gz
        touch {params.prefix}all_chunks.txt.gz.done
        """


rule run_torus:
    input:
        annot="/u/project/gandalm/cindywen/isoform_twas/genotype/all_data/isec_R2_greater_than_3/ancestry/annot/mixed_variant_annot_ensembl_vep.txt.gz",
        fastqtl="/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/sebeta_significant_all_chunks.txt.gz",
    output:
        "/u/project/gandalm/cindywen/isoform_twas/sqtl_new/results/mixed_nominal_40hcp_1e6/torus.out",
    resources:
        mem_gb=4,
        time_min=120,
        num_cores=4,
    shell:
        """
        . /u/local/Modules/default/init/modules.sh
        module load python/3.7.2

        /u/project/gandalm/shared/apps/torus-master/src/torus \
            -d {input.fastqtl} \
            --fastqtl \
            -est \
            -annot {input.annot} \
            > {output[0]}
        """
